Update check_mainnet.yml

diff --git a/.github/workflows/check_mainnet.yml b/.github/workflows/check_mainnet.yml
--- a/.github/workflows/check_mainnet.yml
+++ b/.github/workflows/check_mainnet.yml
@@ -22,17 +22,17 @@ jobs:
           python -m pip install --upgrade pip
           pip install -r requirements.txt
 
-      - name: Notify Slack
-        env:
-          RPC_URL: "https://sapphire.oasis.io"
-          SUBGRAPH_URL: "https://v4.subgraph.sapphire-mainnet.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph"
-          PRIVATE_KEY: "0xb23c44b8118eb7a7f70d21b0d20aed9b05d85d22ac6a0e57697c564da1c35554"
-        run: |
-          output=$(python scripts/check_network.py 1 | grep -E 'FAIL|WARNING|error' || true)
-          fact=$(curl -s https://catfact.ninja/fact | jq -r '.fact')
-          if [ -z "$output" ]; then
-            echo "No output, so no message will be sent to Slack"
-          else
-            message="Mainnet Check script failed: \n${output}\n\n🐱 Anyways here's a random fact about cats 🐱:\n${fact}"
-            curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$message"'"}' ${{ secrets.SLACK_WEBHOOK_URL_MAINNET }}
-          fi
+      # - name: Notify Slack
+      #   env:
+      #     RPC_URL: "https://sapphire.oasis.io"
+      #     SUBGRAPH_URL: "https://v4.subgraph.sapphire-mainnet.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph"
+      #     PRIVATE_KEY: "0xb23c44b8118eb7a7f70d21b0d20aed9b05d85d22ac6a0e57697c564da1c35554"
+      #   run: |
+      #     output=$(python scripts/check_network.py 1 | grep -E 'FAIL|WARNING|error' || true)
+      #     fact=$(curl -s https://catfact.ninja/fact | jq -r '.fact')
+      #     if [ -z "$output" ]; then
+      #       echo "No output, so no message will be sent to Slack"
+      #     else
+      #       message="Mainnet Check script failed: \n${output}\n\n🐱 Anyways here's a random fact about cats 🐱:\n${fact}"
+      #       curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$message"'"}' ${{ secrets.SLACK_WEBHOOK_URL_MAINNET }}
+      #     fi
